// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/5d004be8ba9a0c34e387c249f6873dc68e20ebfa/svgjs.draggable/index.d.ts
declare namespace svgjs {
	export module draggable {
		export interface DragDelta {
			x: number
			y: number
			zoom: number
		}
	}

	export interface Element {
		draggable(): this
		draggable(obj: Object): this
		fixed(): this
		beforedrag: (event: MouseEvent) => any
		dragstart: (delta: draggable.DragDelta, event: MouseEvent) => any
		dragmove: (delta: draggable.DragDelta, event: MouseEvent) => any
		dragend: (delta: draggable.DragDelta, event: MouseEvent) => any

	}
}
